apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: serviceslos.autoscaling.fyp.io
spec:
  group: autoscaling.fyp.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targetDeployment:
                  type: string
                  description: "Name of the Deployment to scale"
                sloLatency:
                  type: integer
                  description: "Target Latency in milliseconds"
                minReplicas:
                  type: integer
                maxReplicas:
                  type: integer
  scope: Namespaced
  names:
    plural: serviceslos
    singular: serviceslo
    kind: ServiceSLO
    shortNames:
    - slo
