apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoscaler-sa
  namespace: thrive-scale
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoscaler-role
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale", "replicasets"]
  verbs: ["get", "list", "update", "patch"]
- apiGroups: ["autoscaling.fyp.io"]
  resources: ["serviceslos"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscaler-binding
subjects:
- kind: ServiceAccount
  name: autoscaler-sa
  namespace: thrive-scale
roleRef:
  kind: ClusterRole
  name: autoscaler-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-autoscaler
  namespace: thrive-scale
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
    spec:
      serviceAccountName: autoscaler-sa
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: controller
        image: loshans/controller:v1
        imagePullPolicy: Never
        env:
          - name: AGGREGATOR_URL
            value: "http://aggregator:8000"
          - name: AGGREGATOR_TIMEOUT_S
            value: "20"
          - name: LOOP_SECONDS
            value: "2"
          - name: TARGET_NAMESPACE
            value: "sock-shop"
          - name: ACTIVE_RPS_THRESHOLD
            value: "0.5"
          - name: DOWNSCALE_RPS_THRESHOLD
            value: "0.5"
          - name: DOWNSCALE_RPS_PER_REPLICA_THRESHOLD
            value: "1.0"
          - name: LOW_DEMAND_STREAK_REQUIRED
            value: "4"
          - name: STRONG_DOWNSCALE_STREAK_REQUIRED
            value: "10"
          - name: SECONDARY_UPSCALE_MIN_RPS
            value: "3.0"
          - name: SECONDARY_UPSCALE_MIN_RPS_PER_REPLICA
            value: "1.0"
          - name: SECONDARY_LOCAL_PRESSURE_STREAK_REQUIRED
            value: "2"
          - name: LATENCY_ONLY_LOCAL_PRESSURE_MIN_RPS
            value: "3.0"
          - name: UPSCALE_COOLDOWN_S
            value: "4"
          - name: DOWNSCALE_COOLDOWN_S
            value: "10"
          - name: RUNQ_FIXED_THRESHOLD_MS
            value: "3.0"
          - name: DOWNSCALE_RUNQ_FACTOR
            value: "0.5"
          - name: DOWNSCALE_RUNQ_MARGIN_MS
            value: "1.0"
          - name: DEPENDENCY_DOMINANCE_RATIO
            value: "1.25"
          - name: OVERLOAD_ERROR_RATE_THRESHOLD
            value: "0.1"
          - name: OVERLOAD_TIMEOUT_RATE_THRESHOLD
            value: "0.02"
          - name: HEALTH_PORT
            value: "28081"
