apiVersion: autoscaling.fyp.io/v1alpha1
kind: ServiceSLO
metadata:
  name: scenario-front-end-slo
  namespace: sock-shop
spec:
  targetDeployment: front-end
  sloLatency: 41
  minReplicas: 1
  maxReplicas: 20
