spec:
  template:
    spec:
      containers:
      - name: catalogue-db
        resources:
          requests:
            cpu: "100m"
            memory: "200Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
