server {
    listen 80;
    server_name localhost;

    location = /dashboard {
        root /usr/share/nginx/html;
        try_files /dashboard.html =404;
    }

    location = /dashboard/ {
        root /usr/share/nginx/html;
        try_files /dashboard.html =404;
    }

    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }
}
