apiVersion: v1
kind: Service
metadata:
  name: bpf-agent       # <--- The Controller looks for this DNS name
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: bpf-agent      # <--- Matches your DaemonSet label "app: bpf-agent"
  ports:
    - protocol: TCP
      port: 5000        # The port the Controller calls
      targetPort: 5000  # The port your Python Agent listens on