apiVersion: v1
kind: Service
metadata:
  name: bpf-agent       
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: bpf-agent      
  ports:
    - protocol: TCP
      port: 5000        
      targetPort: 5000  