apiVersion: v1
kind: ServiceAccount
metadata:
  name: aggregator-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregator-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: aggregator-binding
subjects:
- kind: ServiceAccount
  name: aggregator-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: aggregator-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator
  template:
    metadata:
      labels:
        app: aggregator
    spec:
      serviceAccountName: aggregator-sa
      containers:
      - name: aggregator
        image: local/aggregator:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: aggregator
spec:
  type: LoadBalancer # Expose to your laptop
  selector:
    app: aggregator
  ports:
  - port: 8000
    targetPort: 8000
