apiVersion: v1
kind: ServiceAccount
metadata:
  name: autoscaler-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autoscaler-role
rules:
# --- CORRECTION IS HERE ---
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/scale", "replicasets"] # <--- Moved 'replicasets' here
  verbs: ["get", "list", "update", "patch"]
- apiGroups: [""]
  resources: ["pods"]                                             # <--- Removed 'replicasets' from here
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autoscaler-binding
subjects:
- kind: ServiceAccount
  name: autoscaler-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: autoscaler-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-autoscaler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaler
  template:
    metadata:
      labels:
        app: autoscaler
    spec:
      serviceAccountName: autoscaler-sa
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: autoscaler
        # Make sure this matches your latest build (v5)
        image: autoscaler:v11
        imagePullPolicy: Never